config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  get 'static_pages/home'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'tags/:tag' => 'resources#index', as: 'tag'

  get 'categories/:slug' => 'categories#show_by_slug', as: 'category_slug'

  resources :categories
  resources :resources do
    resources :reviews, except: [:show, :index]
  end

  root 'static_pages#home'

end

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :cost_list, "Costs, separated by commas" %><br>
    <%= f.text_field :cost_list %>
  </div>
  <div class="field">
    <%= f.label :level_list, "Levels, separated by commas" %><br>
    <%= f.text_field :level_list %>
  </div>
  <div class="field">
    <%= f.label :type_list, "Types, separated by commas" %><br>
    <%= f.text_field :type_list %>
  </div>
    <div class="field">
    <%= f.label :url %><br>
    <%= f.text_area :url %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/_resource.html.erb
<div>
    <span><%= link_to resource.title, resource %> </span> |
    <div class="star-rating-readonly" data-score= <%= resource.decorate.avg_rating %> ></div> |
    <%= resource.decorate.count_comments %> reviews
    <p><%= resource.description %> </p>
    <p><span class="label label-primary"> <%= display_tags(resource.cost_list) %> </span>
       <span class="label label-success"> <%= display_tags(resource.type_list) %> </span>
       <span class="label label-warning"> <%= display_tags(resource.level_list) %> </span>
    </p>
</div>

app/views/resources/_resources.html.erb
  <hr />
  <% resources.each do |resource| %>
    <%= render 'resources/resource', resource: resource %>
    <hr />
  <% end %>

app/views/resources/edit.html.erb
<h1>Editing Resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<p id="notice"><%= notice %></p>
<% unless @search_phrase.nil? %>
    <h2> Search results for "<%= @search_phrase %> "</h2>
    <% unless @resources_searched.any? %>
      <h2> : unfortunately your search did not match any courses.</h2>
    <% end %>
<% end %>

<aside class="col-md-3" id="aside">
  <div class="dropdown">
    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
    Choose a category
    <span class="caret"></span>
    </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
    <li><%= link_to "All categories", categories_path %></li>
    <li role="separator" class="divider"></li>
    <% @categories.each do |category| %>
      <li><%= link_to "#{category.title}", category_slug_path(category.slug) %></li>
    <% end %>
  </ul>
</div>

  <div id="tag_cloud">
    <h3> Our tags cloud </h3>
    <% tag_cloud(Resource.cost_counts, %w(css1 css2 css3 css4)) do |tag, css_class| %>
      <%= link_to tag.name, tag_path(tag.name), :class => css_class %>
    <% end %>
    <% tag_cloud(Resource.level_counts, %w(css1 css2 css3 css4)) do |tag, css_class| %>
      <%= link_to tag.name, tag_path(tag.name), :class => css_class %>
    <% end %>
     <% tag_cloud(Resource.type_counts, %w(css1 css2 css3 css4)) do |tag, css_class| %>
      <%= link_to tag.name, tag_path(tag.name), :class => css_class %>
    <% end %>
    <% tag_cloud(Resource.tag_counts, %w(css1 css2 css3 css4)) do |tag, css_class| %>
      <%= link_to tag.name, tag_path(tag.name), :class => css_class %>
    <% end %>
  </div>
</aside>

<section class="col-md-9">
   <% unless @resources_searched.nil? %>
     <%= render 'resources', resources: @resources_searched %>
  <% end %>

<% unless @resources.nil? %>
  <h1>Listing Resources</h1>
      <%= render 'resources', resources: @resources %>
<% end %>
</section>
<br>

<%= link_to 'New Resource', new_resource_path %>
<hr />

app/views/resources/new.html.erb
<h1>New Resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @resource.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @resource.description %>
</p>

<p>
  <strong>Reviews:</strong>
  <% if @resource.reviews.blank? %>
    <h3> No reviews just yet, would you like to add the first? </h3>
  <% else %>
    <% @resource.reviews.reverse.each do |review| %>
      <%= render 'reviews/review', review: review %>
    <% end %>
  <% end %>
  <%= render 'reviews/form' %>

</p>


<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Destroy', @resource, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', resources_path %>